mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info

dns:
  enable: true
  listen: 0.0.0.0:53
  nameserver:
    - 223.5.5.5
    - 119.29.29.29

rules:
  # 自定义规则始终位于最前
  - DOMAIN-SUFFIX,showhype.ai,DIRECT
  # ... 其他固定规则 
